### PR TITLE
Add possibility to use "deagregation" with records where property sta…

### PR DESCRIPTION
**Pull request by slaboszm**
…rts with uppercase (aws js sdk v3 Kinesis record format)

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by slaboszm** [comment]
Hi @IanMeyers , what is the way to release my changes which you a moment ago merge to master branch as new version of [aws-kinesis-agg](https://www.npmjs.com/package/aws-kinesis-agg)?

**Comment by IanMeyers** [comment]
4.2.0 is now published to npm.

**Comment by slaboszm** [comment]
@IanMeyers something went wrong, 4.2.0 do not contains changes from my pull request  (npm package: https://registry.npmjs.org/aws-kinesis-agg/-/aws-kinesis-agg-4.2.0.tgz ), Can you release it again?

**Comment by IanMeyers** [comment]
Nope - NPM doesn't allow version updates. I published 4.2.1 and it had the same issue. Trying to fix.

**Comment by IanMeyers** [comment]
Version 4.2.2 appears to be fully correct and updated.

**Comment by slaboszm** [comment]
@IanMeyers thanks, but i am not sure that the solution which you applied is correct. IMO adding "npm": "^8.3.0", to dependencies causes that every module installed after this will be use local version of npm not global for from developer enviroment. Is this requeried for publication new version? I've checked few modules updated today and no one of them do not have npm in dependencies.

**Comment by IanMeyers** [comment]
with lower versions of NPM, the dependencies do not install correctly and builds are not updated, but I would agree this is not an ideal solution. Placing the dependency in `devDependencies` may also resolve the problem.

**Pull request merged**
