### PR TITLE
Added support for deaggregation in Kinesis Analytics preprocessing lambdas

### LINKED ISSUE #64: Add support for Kinesis Analytics
Tried and tried as I may, this would not function with Kinesis Analytics so I had to modify the object as follows:
```python
    for key, record in enumerate(event['records']):

        decode = record
        decode.update(decode['kinesisStreamRecordMetadata'])
        decode['kinesisSchemaVersion'] = '1.0'
        decode = {'kinesis': record}

        decode = deaggregate_records(decode)
```

Once the object was correct then it worked, however, I am still having an issue splitting records up, but that's an issue for another support forum.

My suggestion is to add support internally so this doesn't have to occur since Kinesis Analytics is still Kinesis...

### PR DESCRIPTION
**Pull request by joebowen**
Added support for deaggregation in Kinesis Analytics preprocessing lambdas due to the fact that the incoming events aren't aggregated into the proper format.  This commit fixes #64.  This is an improvement over PR #69 because it's cleaner and now handles non-aggregated KA records being passed in.

*Issue #, if available:* #64 

*Description of changes:* This is a much cleaner way to handle this issue than the previous PR (#69) and this can handle non-aggregated KA records being passed in.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by joebowen** [comment]
@IanMeyers Let me know what you think but I think this is a better solution.  Thanks again!

**Comment by IanMeyers** [comment]
To prevent churn around previous commits, can you also add: `'approximateArrivalTimestamp': r['kinesis']['approximateArrivalTimestamp'],` to deaggregation ~ line 47?

**Comment by IanMeyers** [comment]
Nevermind will add it to your PR

**Comment by joebowen** [comment]
Sounds good.  Thanks for adding that!

**Pull request merged**
