### PR TITLE
Upgrade protobufjs and use JSON proto file

### PR DESCRIPTION
**Pull request by Strydom**
*Issue #, if available:* https://github.com/awslabs/kinesis-aggregation/issues/99

*Description of changes:*
Bumped protobufjs version and switched to using JSON proto file.
Switching to JSON proto file allows us to require the file and therefore prevent it from being tree shook by webpack.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by IanMeyers** [comment]
In kpl.json, I believe that you will need to set `"rule":"repeated"` for all field descriptors in `AggregatedRecord` and `Tag` in `Record` to be fully compliant with the kpl.proto in the project. Can you please confirm?

**Comment by Strydom** [comment]
All tests pass locally

**Comment by IanMeyers** [comment]
Great stuff. Can you also bump the version in package.json so I can deploy?

**Comment by Strydom** [comment]
4.1.0?

**Comment by IanMeyers** [comment]
Yes pls

**Comment by IanMeyers** [comment]
tagged 4.1.0 on npm

**Pull request merged**
