### PR TITLE
(node) don't spuriously add ExplicitHashKey values to user records

### PR DESCRIPTION
**Pull request by chrislewis**
This fixes issue #48 and includes a new test demonstrating the fix.

Note that this PR requires changes (specifically the dev dependencies) in PR #46.

### CODE REVIEW

**Comment by geronimo-iia** [comment]
@chrislewis hi, you could see https://github.com/awslabs/kinesis-aggregation/pull/42, I've made a lot of changes about test/doc/size limit over 1Mb, etc etc ...

**Comment by chrislewis** [comment]
Hi @geronimo-iia, thanks for pointing that out. That PR is quite large and does not appear to fix what this this one does. Specifically, because of [this line](https://github.com/awslabs/kinesis-aggregation/pull/42/files#diff-315ddbb57a8dd07f9f22c169561b28aeR133). This is the JSON structure that gets serialized to a protobuf blob, but the object passed always has the `explicit_hash_key_index` key with the value of `explicitHashKeyTable[record.explicitHashKey]`, even though `explicitHashKeyTable[record.explicitHashKey]` may be `undefined`. This results in the string value `"undefined"` being written as the explicit hash key within the blob, which is invalid, and (at least) the JVM consumer library fails to parse such records.

As for the rest of it, while the other issues in that PR sound like ones that should be fixed, consider breaking those changes up into smaller PRs, and perhaps leave out the restructuring parts. I can't say I know the success rate of external PRs being merged in this project, but I can say that, in general, larger PRs are far less likely to get attention.

**Comment by geronimo-iia** [comment]
Hi, I'll see your change and try to introduce it in my pr also. I've ever see this issue on this subject, just no much time to spend on it.
I know that large PR are very difficult to merge/accept, ... in fact, we had use this library at work and make huge test and huge change to obtain something which work as needed ... and this is the result: a huge pr :(  
At this point of work, i didn't know how split this work into smaller change (...)

If you use this library actually, you will meet kinesis rejection because message will be over 1Mo. Take care of it :)

Regards

Jerome

**Comment by geronimo-iia** [comment]
Hello, I've added your change in my code base, if you would have a try you could use 'aws-kinesis-agg-fix' version 4.0.2

**Comment by geronimo-iia** [comment]
@chrislewis it was fixed in new release 4.0.2, (my previous pr was accepted)

**Comment by chrislewis** [comment]
@IanMeyers does the closure mean it's been addressed?

**Comment by IanMeyers** [comment]
I took your comment to indicate that it was fixed in version 4.0.2. If that's not the case then will re-open.

**Pull request closed without merging**
