### PR TITLE
NodeJS aggregation, test, example, doc update

### PR DESCRIPTION
**Pull request by geronimo-iia**
Hello,

We made an huge usage of KPL format at work, essentialy with scala/java. So when we start using the nodejs version for other teams, we had few little bad suprise:
- doc not up-to-date (https://github.com/awslabs/kinesis-aggregation/issues/16), but not a big deal (yet)
- aggregation over 1Mo limits (https://github.com/awslabs/kinesis-aggregation/issues/30), more important
- lambda terminaison occurs before processing end (callback mistake ), ...

Here, you could find tested work on huge volume of production data which resolve this 'little' things

- Nodejs Project Basics Fix:
    - package node project with common folder: (lib for source, test for test, and example for ..)
    - add test unit integration
    - update documentation
    - remove java minded stuff
    - simplify use of common/constant/source code 
    - update examples
    - remove dead code, obsolete code/doc
    - add documentation on function
    - use const/let rather than var keyword
    - use forEach rather than map when results array is not needed
    - use resulting array of map (avoid unecessary array creation)

- Issue fixed for nodejs (our initial goal):
    - https://github.com/awslabs/kinesis-aggregation/issues/30: nodejs kinesis encoded record size limit
    - https://github.com/awslabs/kinesis-aggregation/issues/16: obsolete documentation
    - terminaison problem with previously onReadyCallback and afterPutAggregatedRecords on agregate : Lambda terminate before ending,
    when doing some async stuff in onReadyCallback (named encodedRecordHandler now). 

all this could be find in changelog file

Thanks in advance for taking time to review this merge request.

Best regards

Jerome

### CODE REVIEW

**Comment by geronimo-iia** [comment]
@brentnash hello, could you take a little time to review this pull request ? thanks in advance

**Comment by geronimo-iia** [comment]
I pushed a version of this package under the name aws-kinesis-agg-fix (see https://www.npmjs.com/package/aws-kinesis-agg-fix)
I will be happy to remove it when we heard some news about this project/PR... 

Best regards
Jerome

**Comment by axalix** [comment]
Is there a branch anywhere with all these changes, so they can be downloaded locally?

**Comment by geronimo-iia** [comment]
yes either you checkout from
https://github.com/awslabs/kinesis-aggregation/pull/42, or see
https://github.com/geronimo-iia/kinesis-aggregation master branch

**Comment by geronimo-iia** [comment]
@axalix you could also do a  'require('aws-kinesis-agg-fix') in your code if you want to try this code.
(any comment are very welcome :) )

**Comment by IanMeyers** [comment]
This is an awesome contribution. Thanks @geronimo-iia very much for these valuable additions and bug fixes.

**Pull request merged**
